source 'https://rubygems.org'

gem 'nanoc', '<=4.12.3'
gem 'webrick'
gem 'packr'
gem 'kramdown'
gem 'nokogiri'
gem 'nokogiri-pretty'
gem 'rainpress'
gem 'sass'
gem 'image_size'
gem 'pygments.rb'
gem 'builder'
gem 'nanoc-javascript-concatenator'
gem 'uglifier'
gem 'mini_racer'
gem 'activesupport'
gem 'typogruby'

gem 'adsf'

gem 'w3c_validators'
