name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  spellcheck:
    name: Spelling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        show-progress: false
    - uses: codespell-project/actions-codespell@master
      with:
        ignore_words_file: .codespellignore
        path: content/
        skip: content/js
